apiVersion: azure.utsabazure.com/v1
kind: AKSCluster
metadata:
  labels:
    app.kubernetes.io/name: aks-operator
    app.kubernetes.io/managed-by: kustomize
  name: akscluster-sample
spec:
  # TODO(user): Add fields here
  name: "exampleAKS"
  resourceGroup: "exampleResourceGroup"
  location: "eastus"
  nodeCount: 1
  nodeSize: "Standard_D2s_v3"
  kubernetesVersion: "1.30.1"
  autoScaling: true
  minNodeCount: 1
  maxNodeCount: 5
  dnsPrefix: akscluster-sampleone